CREATE TAID_PKBLE user (
  `ID_PK` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) UNIQUE NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  `AGE` TINYINT UNSIGNED,
  `MEMBERSHIP` TINYINT DEFAULT 0,
  `REGISTER_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table shoes (
`ID_PK` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`PD_NAME` VARCHAR(100) NOT NULL,
`DESCRIBE` VARCHAR(300) NOT NULL,
`PRICE` VARCHAR(100) NOT NULL,
`REGISTER_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP,
`UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

select * from shoes;
insert into shoes (PD_NAME, CONTENT, PRICE)
	values ('신발1', '편안한 스니커즈', '120,000');
delete from user where ID_PK = 3;
update user set USERID = pororo where ID_PK = 2;
alter table test_table change column NAME EMAIL VARCHAR(100);
alter table test_table add column ADDRESS VARCHAR(100) AFTER EMAIL;
alter table test_table drop ADDRESS;
drop table test_table;
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '12345678';

DROP TABLE user;

create table user (
`ID_PK` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`USERID` VARCHAR(20) NOT NULL UNIQUE,
`PASSWORD` VARCHAR(20) NOT NULL,
`REGISTER_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP,
`UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);