CREATE TAID_PKBLE user (
  `ID_PK` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) UNIQUE NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  `AGE` TINYINT UNSIGNED,
  `MEMBERSHIP` TINYINT DEFAULT 0,
  `REGISTER_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table boarboardd (
`ID_PK` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`TITLE` VARCHAR(100) NOT NULL,
`CONTENT` VARCHAR(300) NOT NULL,
`REGISTER_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP,
`UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

select * from board;
insert into board (TITLE, CONTENT)
	values ('최두루', 'aaa@daum.com', '7777', '서울 은평구', 32);
delete from user where ID_PK = 3;
update user set AGE = AGE + 1 where ID_PK = 1;
alter table test_table change column NAME EMAIL VARCHAR(100);
alter table test_table add column ADDRESS VARCHAR(100) AFTER EMAIL;
alter table test_table drop ADDRESS;
drop table test_table;
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '12345678';